#!/bin/bash

# Actualizar los repositorios e instalar vsftpd (servidor FTP) y apache2 (servidor Apache HTTP)
apt update
apt install -y vsftpd apache2 bc

# Configurar vsftpd para permitir escritura y subida de archivos al directorio del servidor web
sed -i 's/#write_enable=YES/write_enable=YES/' /etc/vsftpd.conf
sed -i '$a\local_root=/var/www/html' /etc/vsftpd.conf
sed -i 's/#allow_writeable_chroot=YES/allow_writeable_chroot=YES/' /etc/vsftpd.conf
sed -i '$a\annon_root=/var/www/html' /etc/vsftpd.conf
systemctl restart vsftpd

# Configurar Apache HTTP para utilizar el método Worker MPM
sed -i 's/^\(.*\)\(mpm_prefork\|mpm_event\)/# \1\2/' /etc/apache2/apache2.conf
sed -i '/# mpm_worker/s/# //' /etc/apache2/apache2.conf
systemctl restart apache2

#Configurar Permisos de carpetas
chown -R ftp:www-data /var/www/html
chmod -R 777 /var/www/html

# Monitorear el uso del CPU cada 5 minutos
while true; do
    CPU_USAGE=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1}')
    
    # Si el uso del CPU supera el 80%, iniciar otra instancia de Apache HTTP (Worker MPM)
    if [ "$(echo "$CPU_USAGE > 80" | bc)" -eq 1 ]; then
        # Reiniciar Apache HTTP
        systemctl restart apache2
        echo "Se ha iniciado otra instancia de Apache HTTP para balancear la carga debido al alto uso del CPU."
    fi
    
    sleep 300  # Esperar 5 minutos (300 segundos) antes de volver a verificar el uso del CPU
done
